name: face_login
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  # flutter_face_api_beta: ^0.0.88
  flutter_face_api_beta: ^0.0.88
  flutter_face_core: 5.1.0
  flutter: 
    sdk: flutter
  image_picker: ^0.8.7
  path_provider: ^2.0.13

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/images/
  uses-material-design: true

